linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  govet:
    enable-all: true
  errcheck:
    check-blank: true

issues:
  exclude-use-default: false
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
